[package]
name = "sp"
include = [".", "include", "test/tools", "test/tools/process"]
define = ["SP_IMPLEMENTATION", "SP_TEST_IMPLEMENTATION"]
version = "1.6.5"
system_deps = ["m"]

[deps.package]
utest = "1.0.0"
argparse = "1.2.0"

[[profile]]
name = "debug"
cc = "clang"

[[bin]]
name = "amalg"
source = ["test/amalg.c"]

[[bin]]
name = "app"
source = ["test/app.c"]

[[bin]]
name = "context"
source = ["test/context.c"]

[[bin]]
name = "core"
source = ["test/core.c"]

[[bin]]
name = "cv"
source = ["test/cv.c"]

[[bin]]
name = "fmon"
source = ["test/fmon.c"]

[[bin]]
name = "fs"
source = ["test/fs.c"]

[[bin]]
name = "glob"
source = ["test/glob.c"]

[[bin]]
name = "bench-glob"
source = ["test/bench/glob.c"]
include = ["test"]

[[bin]]
name = "ht"
source = ["test/ht.c"]

[[bin]]
name = "io"
source = ["test/io.c"]

[[bin]]
name = "leak"
source = ["test/leak.c"]

[[bin]]
name = "linkage"
source = ["test/linkage.c"]

[[bin]]
name = "process"
source = ["test/tools/process/process.c"]

[[bin]]
name = "ps"
source = ["test/ps.c"]

[[bin]]
name = "stress"
source = ["test/stress.c"]

[[bin]]
name = "time"
source = ["test/time.c"]


[[bin]]
name = "extract_fns"
source = ["doc/tools/extract_fns.c"]

[[bin]]
name = "sleep"
source = ["doc/tools/sleep.c"]
