[package]
name = "sp"
include = [".", "include", "test/tools"]
define = ["SP_IMPLEMENTATION"]
version = "1.6.2"

[deps]
utest = "1.0.0"
argparse = "1.2.0"

[[profile]]
name = "debug"
cc = "tcc"
mode = "debug"
language = "c11"

[[bin]]
name = "app"
source = ["test/app.c"]

[[bin]]
name = "core"
source = ["test/main.c"]

[[bin]]
name = "cv"
source = ["test/cv.c"]

[[bin]]
name = "fmon"
source = ["test/fmon.c"]

[[bin]]
name = "fs"
source = ["test/fs.c"]

[[bin]]
name = "ht"
source = ["test/ht.c"]

[[bin]]
name = "process"
source = ["test/tools/process.c"]

[[bin]]
name = "ps"
source = ["test/ps.c"]

[[bin]]
name = "stress"
source = ["test/stress.c"]

[[bin]]
name = "context"
source = ["test/context.c"]

[[bin]]
name = "linkage"
source = ["test/linkage.c"]

[[bin]]
name = "extract_fns"
source = ["doc/tools/extract_fns.c"]
