[package]
name = "sp"
include = [".", "test/tools"]
define = ["SP_IMPLEMENTATION"]
version = "1.5.3"

[deps]
utest = "1.0.0"
argparse = "1.2.0"

[[profile]]
name = "debug"
# cc = "musl-gcc"
cc = "gcc"
mode = "debug"
language = "c11"
# libc = "cosmopolitan"
linkage = "static"


[[bin]]
name = "app"
source = ["test/app.c"]

[[bin]]
name = "core"
source = ["test/main.c"]

[[bin]]
name = "file_monitor"
source = ["test/file_monitor.c"]

[[bin]]
name = "fs"
source = ["test/fs.c"]

[[bin]]
name = "ht"
source = ["test/ht.c"]

[[bin]]
name = "process"
source = ["test/tools/process.c"]

[[bin]]
name = "ps"
source = ["test/ps.c"]

[[bin]]
name = "stress"
source = ["test/stress.c"]

[[bin]]
name = "extract_fns"
source = ["doc/tools/extract_fns.c"]
